# Generated by Django 3.1 on 2021-05-22 09:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('movies', '0001_initial'), ('movies', '0002_auto_20210425_2359'), ('movies', '0003_auto_20210430_2034'), ('movies', '0004_auto_20210430_2042'), ('movies', '0005_auto_20210501_1747'), ('movies', '0006_auto_20210501_1749'), ('movies', '0007_remove_media_genres'), ('movies', '0008_remove_media_genres'), ('movies', '0009_media_genres'), ('movies', '0010_delete_userprofile'), ('movies', '0011_auto_20210505_1318'), ('movies', '0012_auto_20210507_2302'), ('movies', '0013_auto_20210511_0222'), ('movies', '0014_auto_20210511_0223'), ('movies', '0015_auto_20210511_0223'), ('movies', '0016_auto_20210511_0225'), ('movies', '0017_media_type'), ('movies', '0018_remove_person_uniq')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('file_path', models.FileField(blank=True, upload_to='film_works/', verbose_name='файл')),
                ('creation_date', models.DateField(blank=True, verbose_name='дата создания фильма')),
                ('certificate', models.TextField(blank=True, verbose_name='сертификат')),
                ('rating', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='рейтинг')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
            options={
                'verbose_name': 'Кинопроизведение',
                'verbose_name_plural': 'Кинопроизведения',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
            ],
            options={
                'verbose_name': 'персонаж',
                'verbose_name_plural': 'персонаж',
            },
        ),
        migrations.CreateModel(
            name='PersonMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_type', models.CharField(choices=[('actor', 'актер'), ('writer', 'писатель'), ('director', 'режиссер')], max_length=20, verbose_name='роль')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.media')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'verbose_name': 'участник в создании фильма',
                'verbose_name_plural': 'участики в создании фильма',
                'unique_together': {('person', 'film', 'person_type')},
            },
        ),
        migrations.AddField(
            model_name='media',
            name='persons',
            field=models.ManyToManyField(through='movies.PersonMedia', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='media',
            name='creation_date',
            field=models.DateField(blank=True, default=None, verbose_name='дата создания фильма'),
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'кинопроизведение', 'verbose_name_plural': 'кинопроизведения'},
        ),
        migrations.AlterField(
            model_name='media',
            name='creation_date',
            field=models.DateField(blank=True, default=None, verbose_name='дата создания'),
        ),
        migrations.CreateModel(
            name='GenreMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.media')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
            options={
                'verbose_name': 'жанр фильма',
                'verbose_name_plural': 'жанры фильмов',
                'unique_together': {('genre', 'film')},
            },
        ),
        migrations.RemoveField(
            model_name='media',
            name='genres',
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(through='movies.GenreMedia', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='сертификат'),
        ),
        migrations.AlterField(
            model_name='media',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('film', 'фильм'), ('serial', 'сериал')], default='film', max_length=20, verbose_name='тип'),
            preserve_default=False,
        ),
    ]
