# Generated by Django 3.1 on 2021-04-25 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                ("b", models.CharField(max_length=10, verbose_name="test")),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                ("file_path", models.FileField(blank=True, upload_to="film_works/", verbose_name="файл")),
                ("creation_date", models.DateField(blank=True, verbose_name="дата создания фильма")),
                ("certificate", models.TextField(blank=True, verbose_name="сертификат")),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="рейтинг",
                    ),
                ),
                ("genres", models.ManyToManyField(to="movies.Genre")),
            ],
            options={
                "verbose_name": "Кинопроизведение",
                "verbose_name_plural": "Кинопроизведения",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255, verbose_name="имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="фамилия")),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="PersonMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "person_type",
                    models.CharField(
                        choices=[("actor", "актер"), ("writer", "писатель"), ("director", "режиссер")],
                        max_length=20,
                        verbose_name="тип персонажа",
                    ),
                ),
                ("film", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.media")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.person")),
            ],
            options={
                "verbose_name": "Пресонаж фильмов",
                "verbose_name_plural": "Пресонажи фильмов",
            },
        ),
        migrations.AddField(
            model_name="media",
            name="persons",
            field=models.ManyToManyField(through="movies.PersonMedia", to="movies.Person"),
        ),
    ]
