# Generated by Django 3.1 on 2021-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_squashed_0018_remove_person_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
