# Generated by Django 3.1 on 2021-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_media_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='indexed',
            field=models.BooleanField(default=False, verbose_name='индексирован'),
        ),
    ]
