# Generated by Django 3.1 on 2021-05-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210525_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmedia',
            name='person_type',
            field=models.CharField(choices=[('actor', 'актер'), ('writer', 'писатель'), ('director', 'режиссер')], default='actor', max_length=20, verbose_name='роль'),
        ),
    ]
