# Generated by Django 3.1 on 2021-05-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210526_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmedia',
            options={'verbose_name': 'участник в создании фильма', 'verbose_name_plural': 'участники в создании фильма'},
        ),
    ]
